/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserimagesRouteImport } from './routes/userimages'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as JumpdocLoadingRouteImport } from './routes/jumpdoc-loading'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JumpdocDocIdRouteImport } from './routes/jumpdoc/$docId'
import { Route as ChainChainIdRouteImport } from './routes/chain/$chainId'
import { Route as JumpdocDocIdIndexRouteImport } from './routes/jumpdoc/$docId/index'
import { Route as ChainChainIdIndexRouteImport } from './routes/chain/$chainId/index'
import { Route as ChainChainIdShareRouteImport } from './routes/chain/$chainId/share'
import { Route as ChainChainIdConfigRouteImport } from './routes/chain/$chainId/config'
import { Route as ChainChainIdAddDocRouteImport } from './routes/chain/$chainId/add-doc'
import { Route as ChainChainIdConfigIndexRouteImport } from './routes/chain/$chainId/config/index'
import { Route as ChainChainIdConfigSuppRouteImport } from './routes/chain/$chainId/config/supp'
import { Route as ChainChainIdConfigNotesRouteImport } from './routes/chain/$chainId/config/notes'
import { Route as ChainChainIdConfigDrawbacksRouteImport } from './routes/chain/$chainId/config/drawbacks'
import { Route as ChainChainIdCharCharIdRouteImport } from './routes/chain/$chainId/char/$charId'
import { Route as ChainChainIdConfigSuppIndexRouteImport } from './routes/chain/$chainId/config/supp/index'
import { Route as ChainChainIdConfigSuppSuppIdRouteImport } from './routes/chain/$chainId/config/supp/$suppId'
import { Route as ChainChainIdCharCharIdSummaryRouteImport } from './routes/chain/$chainId/char/$charId/summary'
import { Route as ChainChainIdCharCharIdItemsRouteImport } from './routes/chain/$chainId/char/$charId/items'
import { Route as ChainChainIdCharCharIdSummaryIndexRouteImport } from './routes/chain/$chainId/char/$charId/summary/index'
import { Route as ChainChainIdCharCharIdItemsIndexRouteImport } from './routes/chain/$chainId/char/$charId/items/index'
import { Route as ChainChainIdCharCharIdSummaryPerksRouteImport } from './routes/chain/$chainId/char/$charId/summary/perks'
import { Route as ChainChainIdCharCharIdSummaryNarrativesRouteImport } from './routes/chain/$chainId/char/$charId/summary/narratives'
import { Route as ChainChainIdCharCharIdSummaryAltformsRouteImport } from './routes/chain/$chainId/char/$charId/summary/altforms'
import { Route as ChainChainIdCharCharIdJumpJumpIdRouteImport } from './routes/chain/$chainId/char/$charId/jump/$jumpId'
import { Route as ChainChainIdCharCharIdJumpJumpIdIndexRouteImport } from './routes/chain/$chainId/char/$charId/jump/$jumpId/index'
import { Route as ChainChainIdCharCharIdSummarySuppSupplementIdRouteImport } from './routes/chain/$chainId/char/$charId/summary/supp/$supplementId'
import { Route as ChainChainIdCharCharIdJumpJumpIdPurchasesRouteImport } from './routes/chain/$chainId/char/$charId/jump/$jumpId/purchases'
import { Route as ChainChainIdCharCharIdJumpJumpIdDrawbacksRouteImport } from './routes/chain/$chainId/char/$charId/jump/$jumpId/drawbacks'
import { Route as ChainChainIdCharCharIdJumpJumpIdConfigRouteImport } from './routes/chain/$chainId/char/$charId/jump/$jumpId/config'
import { Route as ChainChainIdCharCharIdJumpJumpIdCompanionsRouteImport } from './routes/chain/$chainId/char/$charId/jump/$jumpId/companions'
import { Route as ChainChainIdCharCharIdItemsSuppSupplementIdRouteImport } from './routes/chain/$chainId/char/$charId/items/supp/$supplementId'
import { Route as ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRouteImport } from './routes/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId'
import { Route as ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRouteImport } from './routes/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId'

const UserimagesRoute = UserimagesRouteImport.update({
  id: '/userimages',
  path: '/userimages',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const JumpdocLoadingRoute = JumpdocLoadingRouteImport.update({
  id: '/jumpdoc-loading',
  path: '/jumpdoc-loading',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JumpdocDocIdRoute = JumpdocDocIdRouteImport.update({
  id: '/jumpdoc/$docId',
  path: '/jumpdoc/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainChainIdRoute = ChainChainIdRouteImport.update({
  id: '/chain/$chainId',
  path: '/chain/$chainId',
  getParentRoute: () => rootRouteImport,
} as any)
const JumpdocDocIdIndexRoute = JumpdocDocIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JumpdocDocIdRoute,
} as any)
const ChainChainIdIndexRoute = ChainChainIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChainChainIdRoute,
} as any)
const ChainChainIdShareRoute = ChainChainIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ChainChainIdRoute,
} as any)
const ChainChainIdConfigRoute = ChainChainIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ChainChainIdRoute,
} as any)
const ChainChainIdAddDocRoute = ChainChainIdAddDocRouteImport.update({
  id: '/add-doc',
  path: '/add-doc',
  getParentRoute: () => ChainChainIdRoute,
} as any)
const ChainChainIdConfigIndexRoute = ChainChainIdConfigIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChainChainIdConfigRoute,
} as any)
const ChainChainIdConfigSuppRoute = ChainChainIdConfigSuppRouteImport.update({
  id: '/supp',
  path: '/supp',
  getParentRoute: () => ChainChainIdConfigRoute,
} as any)
const ChainChainIdConfigNotesRoute = ChainChainIdConfigNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ChainChainIdConfigRoute,
} as any)
const ChainChainIdConfigDrawbacksRoute =
  ChainChainIdConfigDrawbacksRouteImport.update({
    id: '/drawbacks',
    path: '/drawbacks',
    getParentRoute: () => ChainChainIdConfigRoute,
  } as any)
const ChainChainIdCharCharIdRoute = ChainChainIdCharCharIdRouteImport.update({
  id: '/char/$charId',
  path: '/char/$charId',
  getParentRoute: () => ChainChainIdRoute,
} as any)
const ChainChainIdConfigSuppIndexRoute =
  ChainChainIdConfigSuppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChainChainIdConfigSuppRoute,
  } as any)
const ChainChainIdConfigSuppSuppIdRoute =
  ChainChainIdConfigSuppSuppIdRouteImport.update({
    id: '/$suppId',
    path: '/$suppId',
    getParentRoute: () => ChainChainIdConfigSuppRoute,
  } as any)
const ChainChainIdCharCharIdSummaryRoute =
  ChainChainIdCharCharIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => ChainChainIdCharCharIdRoute,
  } as any)
const ChainChainIdCharCharIdItemsRoute =
  ChainChainIdCharCharIdItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => ChainChainIdCharCharIdRoute,
  } as any)
const ChainChainIdCharCharIdSummaryIndexRoute =
  ChainChainIdCharCharIdSummaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChainChainIdCharCharIdSummaryRoute,
  } as any)
const ChainChainIdCharCharIdItemsIndexRoute =
  ChainChainIdCharCharIdItemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChainChainIdCharCharIdItemsRoute,
  } as any)
const ChainChainIdCharCharIdSummaryPerksRoute =
  ChainChainIdCharCharIdSummaryPerksRouteImport.update({
    id: '/perks',
    path: '/perks',
    getParentRoute: () => ChainChainIdCharCharIdSummaryRoute,
  } as any)
const ChainChainIdCharCharIdSummaryNarrativesRoute =
  ChainChainIdCharCharIdSummaryNarrativesRouteImport.update({
    id: '/narratives',
    path: '/narratives',
    getParentRoute: () => ChainChainIdCharCharIdSummaryRoute,
  } as any)
const ChainChainIdCharCharIdSummaryAltformsRoute =
  ChainChainIdCharCharIdSummaryAltformsRouteImport.update({
    id: '/altforms',
    path: '/altforms',
    getParentRoute: () => ChainChainIdCharCharIdSummaryRoute,
  } as any)
const ChainChainIdCharCharIdJumpJumpIdRoute =
  ChainChainIdCharCharIdJumpJumpIdRouteImport.update({
    id: '/jump/$jumpId',
    path: '/jump/$jumpId',
    getParentRoute: () => ChainChainIdCharCharIdRoute,
  } as any)
const ChainChainIdCharCharIdJumpJumpIdIndexRoute =
  ChainChainIdCharCharIdJumpJumpIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ChainChainIdCharCharIdJumpJumpIdRoute,
  } as any)
const ChainChainIdCharCharIdSummarySuppSupplementIdRoute =
  ChainChainIdCharCharIdSummarySuppSupplementIdRouteImport.update({
    id: '/supp/$supplementId',
    path: '/supp/$supplementId',
    getParentRoute: () => ChainChainIdCharCharIdSummaryRoute,
  } as any)
const ChainChainIdCharCharIdJumpJumpIdPurchasesRoute =
  ChainChainIdCharCharIdJumpJumpIdPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => ChainChainIdCharCharIdJumpJumpIdRoute,
  } as any)
const ChainChainIdCharCharIdJumpJumpIdDrawbacksRoute =
  ChainChainIdCharCharIdJumpJumpIdDrawbacksRouteImport.update({
    id: '/drawbacks',
    path: '/drawbacks',
    getParentRoute: () => ChainChainIdCharCharIdJumpJumpIdRoute,
  } as any)
const ChainChainIdCharCharIdJumpJumpIdConfigRoute =
  ChainChainIdCharCharIdJumpJumpIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => ChainChainIdCharCharIdJumpJumpIdRoute,
  } as any)
const ChainChainIdCharCharIdJumpJumpIdCompanionsRoute =
  ChainChainIdCharCharIdJumpJumpIdCompanionsRouteImport.update({
    id: '/companions',
    path: '/companions',
    getParentRoute: () => ChainChainIdCharCharIdJumpJumpIdRoute,
  } as any)
const ChainChainIdCharCharIdItemsSuppSupplementIdRoute =
  ChainChainIdCharCharIdItemsSuppSupplementIdRouteImport.update({
    id: '/supp/$supplementId',
    path: '/supp/$supplementId',
    getParentRoute: () => ChainChainIdCharCharIdItemsRoute,
  } as any)
const ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRoute =
  ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRouteImport.update({
    id: '/supp/$supplementId',
    path: '/supp/$supplementId',
    getParentRoute: () => ChainChainIdCharCharIdJumpJumpIdRoute,
  } as any)
const ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRoute =
  ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRouteImport.update({
    id: '/subsystem/$subtypeId',
    path: '/subsystem/$subtypeId',
    getParentRoute: () => ChainChainIdCharCharIdJumpJumpIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/jumpdoc-loading': typeof JumpdocLoadingRoute
  '/portal': typeof PortalRoute
  '/purchases': typeof PurchasesRoute
  '/userimages': typeof UserimagesRoute
  '/chain/$chainId': typeof ChainChainIdRouteWithChildren
  '/jumpdoc/$docId': typeof JumpdocDocIdRouteWithChildren
  '/chain/$chainId/add-doc': typeof ChainChainIdAddDocRoute
  '/chain/$chainId/config': typeof ChainChainIdConfigRouteWithChildren
  '/chain/$chainId/share': typeof ChainChainIdShareRoute
  '/chain/$chainId/': typeof ChainChainIdIndexRoute
  '/jumpdoc/$docId/': typeof JumpdocDocIdIndexRoute
  '/chain/$chainId/char/$charId': typeof ChainChainIdCharCharIdRouteWithChildren
  '/chain/$chainId/config/drawbacks': typeof ChainChainIdConfigDrawbacksRoute
  '/chain/$chainId/config/notes': typeof ChainChainIdConfigNotesRoute
  '/chain/$chainId/config/supp': typeof ChainChainIdConfigSuppRouteWithChildren
  '/chain/$chainId/config/': typeof ChainChainIdConfigIndexRoute
  '/chain/$chainId/char/$charId/items': typeof ChainChainIdCharCharIdItemsRouteWithChildren
  '/chain/$chainId/char/$charId/summary': typeof ChainChainIdCharCharIdSummaryRouteWithChildren
  '/chain/$chainId/config/supp/$suppId': typeof ChainChainIdConfigSuppSuppIdRoute
  '/chain/$chainId/config/supp/': typeof ChainChainIdConfigSuppIndexRoute
  '/chain/$chainId/char/$charId/jump/$jumpId': typeof ChainChainIdCharCharIdJumpJumpIdRouteWithChildren
  '/chain/$chainId/char/$charId/summary/altforms': typeof ChainChainIdCharCharIdSummaryAltformsRoute
  '/chain/$chainId/char/$charId/summary/narratives': typeof ChainChainIdCharCharIdSummaryNarrativesRoute
  '/chain/$chainId/char/$charId/summary/perks': typeof ChainChainIdCharCharIdSummaryPerksRoute
  '/chain/$chainId/char/$charId/items/': typeof ChainChainIdCharCharIdItemsIndexRoute
  '/chain/$chainId/char/$charId/summary/': typeof ChainChainIdCharCharIdSummaryIndexRoute
  '/chain/$chainId/char/$charId/items/supp/$supplementId': typeof ChainChainIdCharCharIdItemsSuppSupplementIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/companions': typeof ChainChainIdCharCharIdJumpJumpIdCompanionsRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/config': typeof ChainChainIdCharCharIdJumpJumpIdConfigRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks': typeof ChainChainIdCharCharIdJumpJumpIdDrawbacksRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/purchases': typeof ChainChainIdCharCharIdJumpJumpIdPurchasesRoute
  '/chain/$chainId/char/$charId/summary/supp/$supplementId': typeof ChainChainIdCharCharIdSummarySuppSupplementIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/': typeof ChainChainIdCharCharIdJumpJumpIdIndexRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId': typeof ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId': typeof ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/jumpdoc-loading': typeof JumpdocLoadingRoute
  '/portal': typeof PortalRoute
  '/purchases': typeof PurchasesRoute
  '/userimages': typeof UserimagesRoute
  '/chain/$chainId/add-doc': typeof ChainChainIdAddDocRoute
  '/chain/$chainId/share': typeof ChainChainIdShareRoute
  '/chain/$chainId': typeof ChainChainIdIndexRoute
  '/jumpdoc/$docId': typeof JumpdocDocIdIndexRoute
  '/chain/$chainId/char/$charId': typeof ChainChainIdCharCharIdRouteWithChildren
  '/chain/$chainId/config/drawbacks': typeof ChainChainIdConfigDrawbacksRoute
  '/chain/$chainId/config/notes': typeof ChainChainIdConfigNotesRoute
  '/chain/$chainId/config': typeof ChainChainIdConfigIndexRoute
  '/chain/$chainId/config/supp/$suppId': typeof ChainChainIdConfigSuppSuppIdRoute
  '/chain/$chainId/config/supp': typeof ChainChainIdConfigSuppIndexRoute
  '/chain/$chainId/char/$charId/summary/altforms': typeof ChainChainIdCharCharIdSummaryAltformsRoute
  '/chain/$chainId/char/$charId/summary/narratives': typeof ChainChainIdCharCharIdSummaryNarrativesRoute
  '/chain/$chainId/char/$charId/summary/perks': typeof ChainChainIdCharCharIdSummaryPerksRoute
  '/chain/$chainId/char/$charId/items': typeof ChainChainIdCharCharIdItemsIndexRoute
  '/chain/$chainId/char/$charId/summary': typeof ChainChainIdCharCharIdSummaryIndexRoute
  '/chain/$chainId/char/$charId/items/supp/$supplementId': typeof ChainChainIdCharCharIdItemsSuppSupplementIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/companions': typeof ChainChainIdCharCharIdJumpJumpIdCompanionsRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/config': typeof ChainChainIdCharCharIdJumpJumpIdConfigRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks': typeof ChainChainIdCharCharIdJumpJumpIdDrawbacksRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/purchases': typeof ChainChainIdCharCharIdJumpJumpIdPurchasesRoute
  '/chain/$chainId/char/$charId/summary/supp/$supplementId': typeof ChainChainIdCharCharIdSummarySuppSupplementIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId': typeof ChainChainIdCharCharIdJumpJumpIdIndexRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId': typeof ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId': typeof ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/jumpdoc-loading': typeof JumpdocLoadingRoute
  '/portal': typeof PortalRoute
  '/purchases': typeof PurchasesRoute
  '/userimages': typeof UserimagesRoute
  '/chain/$chainId': typeof ChainChainIdRouteWithChildren
  '/jumpdoc/$docId': typeof JumpdocDocIdRouteWithChildren
  '/chain/$chainId/add-doc': typeof ChainChainIdAddDocRoute
  '/chain/$chainId/config': typeof ChainChainIdConfigRouteWithChildren
  '/chain/$chainId/share': typeof ChainChainIdShareRoute
  '/chain/$chainId/': typeof ChainChainIdIndexRoute
  '/jumpdoc/$docId/': typeof JumpdocDocIdIndexRoute
  '/chain/$chainId/char/$charId': typeof ChainChainIdCharCharIdRouteWithChildren
  '/chain/$chainId/config/drawbacks': typeof ChainChainIdConfigDrawbacksRoute
  '/chain/$chainId/config/notes': typeof ChainChainIdConfigNotesRoute
  '/chain/$chainId/config/supp': typeof ChainChainIdConfigSuppRouteWithChildren
  '/chain/$chainId/config/': typeof ChainChainIdConfigIndexRoute
  '/chain/$chainId/char/$charId/items': typeof ChainChainIdCharCharIdItemsRouteWithChildren
  '/chain/$chainId/char/$charId/summary': typeof ChainChainIdCharCharIdSummaryRouteWithChildren
  '/chain/$chainId/config/supp/$suppId': typeof ChainChainIdConfigSuppSuppIdRoute
  '/chain/$chainId/config/supp/': typeof ChainChainIdConfigSuppIndexRoute
  '/chain/$chainId/char/$charId/jump/$jumpId': typeof ChainChainIdCharCharIdJumpJumpIdRouteWithChildren
  '/chain/$chainId/char/$charId/summary/altforms': typeof ChainChainIdCharCharIdSummaryAltformsRoute
  '/chain/$chainId/char/$charId/summary/narratives': typeof ChainChainIdCharCharIdSummaryNarrativesRoute
  '/chain/$chainId/char/$charId/summary/perks': typeof ChainChainIdCharCharIdSummaryPerksRoute
  '/chain/$chainId/char/$charId/items/': typeof ChainChainIdCharCharIdItemsIndexRoute
  '/chain/$chainId/char/$charId/summary/': typeof ChainChainIdCharCharIdSummaryIndexRoute
  '/chain/$chainId/char/$charId/items/supp/$supplementId': typeof ChainChainIdCharCharIdItemsSuppSupplementIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/companions': typeof ChainChainIdCharCharIdJumpJumpIdCompanionsRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/config': typeof ChainChainIdCharCharIdJumpJumpIdConfigRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks': typeof ChainChainIdCharCharIdJumpJumpIdDrawbacksRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/purchases': typeof ChainChainIdCharCharIdJumpJumpIdPurchasesRoute
  '/chain/$chainId/char/$charId/summary/supp/$supplementId': typeof ChainChainIdCharCharIdSummarySuppSupplementIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/': typeof ChainChainIdCharCharIdJumpJumpIdIndexRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId': typeof ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRoute
  '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId': typeof ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/guide'
    | '/jumpdoc-loading'
    | '/portal'
    | '/purchases'
    | '/userimages'
    | '/chain/$chainId'
    | '/jumpdoc/$docId'
    | '/chain/$chainId/add-doc'
    | '/chain/$chainId/config'
    | '/chain/$chainId/share'
    | '/chain/$chainId/'
    | '/jumpdoc/$docId/'
    | '/chain/$chainId/char/$charId'
    | '/chain/$chainId/config/drawbacks'
    | '/chain/$chainId/config/notes'
    | '/chain/$chainId/config/supp'
    | '/chain/$chainId/config/'
    | '/chain/$chainId/char/$charId/items'
    | '/chain/$chainId/char/$charId/summary'
    | '/chain/$chainId/config/supp/$suppId'
    | '/chain/$chainId/config/supp/'
    | '/chain/$chainId/char/$charId/jump/$jumpId'
    | '/chain/$chainId/char/$charId/summary/altforms'
    | '/chain/$chainId/char/$charId/summary/narratives'
    | '/chain/$chainId/char/$charId/summary/perks'
    | '/chain/$chainId/char/$charId/items/'
    | '/chain/$chainId/char/$charId/summary/'
    | '/chain/$chainId/char/$charId/items/supp/$supplementId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/companions'
    | '/chain/$chainId/char/$charId/jump/$jumpId/config'
    | '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks'
    | '/chain/$chainId/char/$charId/jump/$jumpId/purchases'
    | '/chain/$chainId/char/$charId/summary/supp/$supplementId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/'
    | '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/guide'
    | '/jumpdoc-loading'
    | '/portal'
    | '/purchases'
    | '/userimages'
    | '/chain/$chainId/add-doc'
    | '/chain/$chainId/share'
    | '/chain/$chainId'
    | '/jumpdoc/$docId'
    | '/chain/$chainId/char/$charId'
    | '/chain/$chainId/config/drawbacks'
    | '/chain/$chainId/config/notes'
    | '/chain/$chainId/config'
    | '/chain/$chainId/config/supp/$suppId'
    | '/chain/$chainId/config/supp'
    | '/chain/$chainId/char/$charId/summary/altforms'
    | '/chain/$chainId/char/$charId/summary/narratives'
    | '/chain/$chainId/char/$charId/summary/perks'
    | '/chain/$chainId/char/$charId/items'
    | '/chain/$chainId/char/$charId/summary'
    | '/chain/$chainId/char/$charId/items/supp/$supplementId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/companions'
    | '/chain/$chainId/char/$charId/jump/$jumpId/config'
    | '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks'
    | '/chain/$chainId/char/$charId/jump/$jumpId/purchases'
    | '/chain/$chainId/char/$charId/summary/supp/$supplementId'
    | '/chain/$chainId/char/$charId/jump/$jumpId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/guide'
    | '/jumpdoc-loading'
    | '/portal'
    | '/purchases'
    | '/userimages'
    | '/chain/$chainId'
    | '/jumpdoc/$docId'
    | '/chain/$chainId/add-doc'
    | '/chain/$chainId/config'
    | '/chain/$chainId/share'
    | '/chain/$chainId/'
    | '/jumpdoc/$docId/'
    | '/chain/$chainId/char/$charId'
    | '/chain/$chainId/config/drawbacks'
    | '/chain/$chainId/config/notes'
    | '/chain/$chainId/config/supp'
    | '/chain/$chainId/config/'
    | '/chain/$chainId/char/$charId/items'
    | '/chain/$chainId/char/$charId/summary'
    | '/chain/$chainId/config/supp/$suppId'
    | '/chain/$chainId/config/supp/'
    | '/chain/$chainId/char/$charId/jump/$jumpId'
    | '/chain/$chainId/char/$charId/summary/altforms'
    | '/chain/$chainId/char/$charId/summary/narratives'
    | '/chain/$chainId/char/$charId/summary/perks'
    | '/chain/$chainId/char/$charId/items/'
    | '/chain/$chainId/char/$charId/summary/'
    | '/chain/$chainId/char/$charId/items/supp/$supplementId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/companions'
    | '/chain/$chainId/char/$charId/jump/$jumpId/config'
    | '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks'
    | '/chain/$chainId/char/$charId/jump/$jumpId/purchases'
    | '/chain/$chainId/char/$charId/summary/supp/$supplementId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/'
    | '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId'
    | '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  GuideRoute: typeof GuideRoute
  JumpdocLoadingRoute: typeof JumpdocLoadingRoute
  PortalRoute: typeof PortalRoute
  PurchasesRoute: typeof PurchasesRoute
  UserimagesRoute: typeof UserimagesRoute
  ChainChainIdRoute: typeof ChainChainIdRouteWithChildren
  JumpdocDocIdRoute: typeof JumpdocDocIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userimages': {
      id: '/userimages'
      path: '/userimages'
      fullPath: '/userimages'
      preLoaderRoute: typeof UserimagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jumpdoc-loading': {
      id: '/jumpdoc-loading'
      path: '/jumpdoc-loading'
      fullPath: '/jumpdoc-loading'
      preLoaderRoute: typeof JumpdocLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jumpdoc/$docId': {
      id: '/jumpdoc/$docId'
      path: '/jumpdoc/$docId'
      fullPath: '/jumpdoc/$docId'
      preLoaderRoute: typeof JumpdocDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain/$chainId': {
      id: '/chain/$chainId'
      path: '/chain/$chainId'
      fullPath: '/chain/$chainId'
      preLoaderRoute: typeof ChainChainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jumpdoc/$docId/': {
      id: '/jumpdoc/$docId/'
      path: '/'
      fullPath: '/jumpdoc/$docId/'
      preLoaderRoute: typeof JumpdocDocIdIndexRouteImport
      parentRoute: typeof JumpdocDocIdRoute
    }
    '/chain/$chainId/': {
      id: '/chain/$chainId/'
      path: '/'
      fullPath: '/chain/$chainId/'
      preLoaderRoute: typeof ChainChainIdIndexRouteImport
      parentRoute: typeof ChainChainIdRoute
    }
    '/chain/$chainId/share': {
      id: '/chain/$chainId/share'
      path: '/share'
      fullPath: '/chain/$chainId/share'
      preLoaderRoute: typeof ChainChainIdShareRouteImport
      parentRoute: typeof ChainChainIdRoute
    }
    '/chain/$chainId/config': {
      id: '/chain/$chainId/config'
      path: '/config'
      fullPath: '/chain/$chainId/config'
      preLoaderRoute: typeof ChainChainIdConfigRouteImport
      parentRoute: typeof ChainChainIdRoute
    }
    '/chain/$chainId/add-doc': {
      id: '/chain/$chainId/add-doc'
      path: '/add-doc'
      fullPath: '/chain/$chainId/add-doc'
      preLoaderRoute: typeof ChainChainIdAddDocRouteImport
      parentRoute: typeof ChainChainIdRoute
    }
    '/chain/$chainId/config/': {
      id: '/chain/$chainId/config/'
      path: '/'
      fullPath: '/chain/$chainId/config/'
      preLoaderRoute: typeof ChainChainIdConfigIndexRouteImport
      parentRoute: typeof ChainChainIdConfigRoute
    }
    '/chain/$chainId/config/supp': {
      id: '/chain/$chainId/config/supp'
      path: '/supp'
      fullPath: '/chain/$chainId/config/supp'
      preLoaderRoute: typeof ChainChainIdConfigSuppRouteImport
      parentRoute: typeof ChainChainIdConfigRoute
    }
    '/chain/$chainId/config/notes': {
      id: '/chain/$chainId/config/notes'
      path: '/notes'
      fullPath: '/chain/$chainId/config/notes'
      preLoaderRoute: typeof ChainChainIdConfigNotesRouteImport
      parentRoute: typeof ChainChainIdConfigRoute
    }
    '/chain/$chainId/config/drawbacks': {
      id: '/chain/$chainId/config/drawbacks'
      path: '/drawbacks'
      fullPath: '/chain/$chainId/config/drawbacks'
      preLoaderRoute: typeof ChainChainIdConfigDrawbacksRouteImport
      parentRoute: typeof ChainChainIdConfigRoute
    }
    '/chain/$chainId/char/$charId': {
      id: '/chain/$chainId/char/$charId'
      path: '/char/$charId'
      fullPath: '/chain/$chainId/char/$charId'
      preLoaderRoute: typeof ChainChainIdCharCharIdRouteImport
      parentRoute: typeof ChainChainIdRoute
    }
    '/chain/$chainId/config/supp/': {
      id: '/chain/$chainId/config/supp/'
      path: '/'
      fullPath: '/chain/$chainId/config/supp/'
      preLoaderRoute: typeof ChainChainIdConfigSuppIndexRouteImport
      parentRoute: typeof ChainChainIdConfigSuppRoute
    }
    '/chain/$chainId/config/supp/$suppId': {
      id: '/chain/$chainId/config/supp/$suppId'
      path: '/$suppId'
      fullPath: '/chain/$chainId/config/supp/$suppId'
      preLoaderRoute: typeof ChainChainIdConfigSuppSuppIdRouteImport
      parentRoute: typeof ChainChainIdConfigSuppRoute
    }
    '/chain/$chainId/char/$charId/summary': {
      id: '/chain/$chainId/char/$charId/summary'
      path: '/summary'
      fullPath: '/chain/$chainId/char/$charId/summary'
      preLoaderRoute: typeof ChainChainIdCharCharIdSummaryRouteImport
      parentRoute: typeof ChainChainIdCharCharIdRoute
    }
    '/chain/$chainId/char/$charId/items': {
      id: '/chain/$chainId/char/$charId/items'
      path: '/items'
      fullPath: '/chain/$chainId/char/$charId/items'
      preLoaderRoute: typeof ChainChainIdCharCharIdItemsRouteImport
      parentRoute: typeof ChainChainIdCharCharIdRoute
    }
    '/chain/$chainId/char/$charId/summary/': {
      id: '/chain/$chainId/char/$charId/summary/'
      path: '/'
      fullPath: '/chain/$chainId/char/$charId/summary/'
      preLoaderRoute: typeof ChainChainIdCharCharIdSummaryIndexRouteImport
      parentRoute: typeof ChainChainIdCharCharIdSummaryRoute
    }
    '/chain/$chainId/char/$charId/items/': {
      id: '/chain/$chainId/char/$charId/items/'
      path: '/'
      fullPath: '/chain/$chainId/char/$charId/items/'
      preLoaderRoute: typeof ChainChainIdCharCharIdItemsIndexRouteImport
      parentRoute: typeof ChainChainIdCharCharIdItemsRoute
    }
    '/chain/$chainId/char/$charId/summary/perks': {
      id: '/chain/$chainId/char/$charId/summary/perks'
      path: '/perks'
      fullPath: '/chain/$chainId/char/$charId/summary/perks'
      preLoaderRoute: typeof ChainChainIdCharCharIdSummaryPerksRouteImport
      parentRoute: typeof ChainChainIdCharCharIdSummaryRoute
    }
    '/chain/$chainId/char/$charId/summary/narratives': {
      id: '/chain/$chainId/char/$charId/summary/narratives'
      path: '/narratives'
      fullPath: '/chain/$chainId/char/$charId/summary/narratives'
      preLoaderRoute: typeof ChainChainIdCharCharIdSummaryNarrativesRouteImport
      parentRoute: typeof ChainChainIdCharCharIdSummaryRoute
    }
    '/chain/$chainId/char/$charId/summary/altforms': {
      id: '/chain/$chainId/char/$charId/summary/altforms'
      path: '/altforms'
      fullPath: '/chain/$chainId/char/$charId/summary/altforms'
      preLoaderRoute: typeof ChainChainIdCharCharIdSummaryAltformsRouteImport
      parentRoute: typeof ChainChainIdCharCharIdSummaryRoute
    }
    '/chain/$chainId/char/$charId/jump/$jumpId': {
      id: '/chain/$chainId/char/$charId/jump/$jumpId'
      path: '/jump/$jumpId'
      fullPath: '/chain/$chainId/char/$charId/jump/$jumpId'
      preLoaderRoute: typeof ChainChainIdCharCharIdJumpJumpIdRouteImport
      parentRoute: typeof ChainChainIdCharCharIdRoute
    }
    '/chain/$chainId/char/$charId/jump/$jumpId/': {
      id: '/chain/$chainId/char/$charId/jump/$jumpId/'
      path: '/'
      fullPath: '/chain/$chainId/char/$charId/jump/$jumpId/'
      preLoaderRoute: typeof ChainChainIdCharCharIdJumpJumpIdIndexRouteImport
      parentRoute: typeof ChainChainIdCharCharIdJumpJumpIdRoute
    }
    '/chain/$chainId/char/$charId/summary/supp/$supplementId': {
      id: '/chain/$chainId/char/$charId/summary/supp/$supplementId'
      path: '/supp/$supplementId'
      fullPath: '/chain/$chainId/char/$charId/summary/supp/$supplementId'
      preLoaderRoute: typeof ChainChainIdCharCharIdSummarySuppSupplementIdRouteImport
      parentRoute: typeof ChainChainIdCharCharIdSummaryRoute
    }
    '/chain/$chainId/char/$charId/jump/$jumpId/purchases': {
      id: '/chain/$chainId/char/$charId/jump/$jumpId/purchases'
      path: '/purchases'
      fullPath: '/chain/$chainId/char/$charId/jump/$jumpId/purchases'
      preLoaderRoute: typeof ChainChainIdCharCharIdJumpJumpIdPurchasesRouteImport
      parentRoute: typeof ChainChainIdCharCharIdJumpJumpIdRoute
    }
    '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks': {
      id: '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks'
      path: '/drawbacks'
      fullPath: '/chain/$chainId/char/$charId/jump/$jumpId/drawbacks'
      preLoaderRoute: typeof ChainChainIdCharCharIdJumpJumpIdDrawbacksRouteImport
      parentRoute: typeof ChainChainIdCharCharIdJumpJumpIdRoute
    }
    '/chain/$chainId/char/$charId/jump/$jumpId/config': {
      id: '/chain/$chainId/char/$charId/jump/$jumpId/config'
      path: '/config'
      fullPath: '/chain/$chainId/char/$charId/jump/$jumpId/config'
      preLoaderRoute: typeof ChainChainIdCharCharIdJumpJumpIdConfigRouteImport
      parentRoute: typeof ChainChainIdCharCharIdJumpJumpIdRoute
    }
    '/chain/$chainId/char/$charId/jump/$jumpId/companions': {
      id: '/chain/$chainId/char/$charId/jump/$jumpId/companions'
      path: '/companions'
      fullPath: '/chain/$chainId/char/$charId/jump/$jumpId/companions'
      preLoaderRoute: typeof ChainChainIdCharCharIdJumpJumpIdCompanionsRouteImport
      parentRoute: typeof ChainChainIdCharCharIdJumpJumpIdRoute
    }
    '/chain/$chainId/char/$charId/items/supp/$supplementId': {
      id: '/chain/$chainId/char/$charId/items/supp/$supplementId'
      path: '/supp/$supplementId'
      fullPath: '/chain/$chainId/char/$charId/items/supp/$supplementId'
      preLoaderRoute: typeof ChainChainIdCharCharIdItemsSuppSupplementIdRouteImport
      parentRoute: typeof ChainChainIdCharCharIdItemsRoute
    }
    '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId': {
      id: '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId'
      path: '/supp/$supplementId'
      fullPath: '/chain/$chainId/char/$charId/jump/$jumpId/supp/$supplementId'
      preLoaderRoute: typeof ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRouteImport
      parentRoute: typeof ChainChainIdCharCharIdJumpJumpIdRoute
    }
    '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId': {
      id: '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId'
      path: '/subsystem/$subtypeId'
      fullPath: '/chain/$chainId/char/$charId/jump/$jumpId/subsystem/$subtypeId'
      preLoaderRoute: typeof ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRouteImport
      parentRoute: typeof ChainChainIdCharCharIdJumpJumpIdRoute
    }
  }
}

interface ChainChainIdConfigSuppRouteChildren {
  ChainChainIdConfigSuppSuppIdRoute: typeof ChainChainIdConfigSuppSuppIdRoute
  ChainChainIdConfigSuppIndexRoute: typeof ChainChainIdConfigSuppIndexRoute
}

const ChainChainIdConfigSuppRouteChildren: ChainChainIdConfigSuppRouteChildren =
  {
    ChainChainIdConfigSuppSuppIdRoute: ChainChainIdConfigSuppSuppIdRoute,
    ChainChainIdConfigSuppIndexRoute: ChainChainIdConfigSuppIndexRoute,
  }

const ChainChainIdConfigSuppRouteWithChildren =
  ChainChainIdConfigSuppRoute._addFileChildren(
    ChainChainIdConfigSuppRouteChildren,
  )

interface ChainChainIdConfigRouteChildren {
  ChainChainIdConfigDrawbacksRoute: typeof ChainChainIdConfigDrawbacksRoute
  ChainChainIdConfigNotesRoute: typeof ChainChainIdConfigNotesRoute
  ChainChainIdConfigSuppRoute: typeof ChainChainIdConfigSuppRouteWithChildren
  ChainChainIdConfigIndexRoute: typeof ChainChainIdConfigIndexRoute
}

const ChainChainIdConfigRouteChildren: ChainChainIdConfigRouteChildren = {
  ChainChainIdConfigDrawbacksRoute: ChainChainIdConfigDrawbacksRoute,
  ChainChainIdConfigNotesRoute: ChainChainIdConfigNotesRoute,
  ChainChainIdConfigSuppRoute: ChainChainIdConfigSuppRouteWithChildren,
  ChainChainIdConfigIndexRoute: ChainChainIdConfigIndexRoute,
}

const ChainChainIdConfigRouteWithChildren =
  ChainChainIdConfigRoute._addFileChildren(ChainChainIdConfigRouteChildren)

interface ChainChainIdCharCharIdItemsRouteChildren {
  ChainChainIdCharCharIdItemsIndexRoute: typeof ChainChainIdCharCharIdItemsIndexRoute
  ChainChainIdCharCharIdItemsSuppSupplementIdRoute: typeof ChainChainIdCharCharIdItemsSuppSupplementIdRoute
}

const ChainChainIdCharCharIdItemsRouteChildren: ChainChainIdCharCharIdItemsRouteChildren =
  {
    ChainChainIdCharCharIdItemsIndexRoute:
      ChainChainIdCharCharIdItemsIndexRoute,
    ChainChainIdCharCharIdItemsSuppSupplementIdRoute:
      ChainChainIdCharCharIdItemsSuppSupplementIdRoute,
  }

const ChainChainIdCharCharIdItemsRouteWithChildren =
  ChainChainIdCharCharIdItemsRoute._addFileChildren(
    ChainChainIdCharCharIdItemsRouteChildren,
  )

interface ChainChainIdCharCharIdSummaryRouteChildren {
  ChainChainIdCharCharIdSummaryAltformsRoute: typeof ChainChainIdCharCharIdSummaryAltformsRoute
  ChainChainIdCharCharIdSummaryNarrativesRoute: typeof ChainChainIdCharCharIdSummaryNarrativesRoute
  ChainChainIdCharCharIdSummaryPerksRoute: typeof ChainChainIdCharCharIdSummaryPerksRoute
  ChainChainIdCharCharIdSummaryIndexRoute: typeof ChainChainIdCharCharIdSummaryIndexRoute
  ChainChainIdCharCharIdSummarySuppSupplementIdRoute: typeof ChainChainIdCharCharIdSummarySuppSupplementIdRoute
}

const ChainChainIdCharCharIdSummaryRouteChildren: ChainChainIdCharCharIdSummaryRouteChildren =
  {
    ChainChainIdCharCharIdSummaryAltformsRoute:
      ChainChainIdCharCharIdSummaryAltformsRoute,
    ChainChainIdCharCharIdSummaryNarrativesRoute:
      ChainChainIdCharCharIdSummaryNarrativesRoute,
    ChainChainIdCharCharIdSummaryPerksRoute:
      ChainChainIdCharCharIdSummaryPerksRoute,
    ChainChainIdCharCharIdSummaryIndexRoute:
      ChainChainIdCharCharIdSummaryIndexRoute,
    ChainChainIdCharCharIdSummarySuppSupplementIdRoute:
      ChainChainIdCharCharIdSummarySuppSupplementIdRoute,
  }

const ChainChainIdCharCharIdSummaryRouteWithChildren =
  ChainChainIdCharCharIdSummaryRoute._addFileChildren(
    ChainChainIdCharCharIdSummaryRouteChildren,
  )

interface ChainChainIdCharCharIdJumpJumpIdRouteChildren {
  ChainChainIdCharCharIdJumpJumpIdCompanionsRoute: typeof ChainChainIdCharCharIdJumpJumpIdCompanionsRoute
  ChainChainIdCharCharIdJumpJumpIdConfigRoute: typeof ChainChainIdCharCharIdJumpJumpIdConfigRoute
  ChainChainIdCharCharIdJumpJumpIdDrawbacksRoute: typeof ChainChainIdCharCharIdJumpJumpIdDrawbacksRoute
  ChainChainIdCharCharIdJumpJumpIdPurchasesRoute: typeof ChainChainIdCharCharIdJumpJumpIdPurchasesRoute
  ChainChainIdCharCharIdJumpJumpIdIndexRoute: typeof ChainChainIdCharCharIdJumpJumpIdIndexRoute
  ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRoute: typeof ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRoute
  ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRoute: typeof ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRoute
}

const ChainChainIdCharCharIdJumpJumpIdRouteChildren: ChainChainIdCharCharIdJumpJumpIdRouteChildren =
  {
    ChainChainIdCharCharIdJumpJumpIdCompanionsRoute:
      ChainChainIdCharCharIdJumpJumpIdCompanionsRoute,
    ChainChainIdCharCharIdJumpJumpIdConfigRoute:
      ChainChainIdCharCharIdJumpJumpIdConfigRoute,
    ChainChainIdCharCharIdJumpJumpIdDrawbacksRoute:
      ChainChainIdCharCharIdJumpJumpIdDrawbacksRoute,
    ChainChainIdCharCharIdJumpJumpIdPurchasesRoute:
      ChainChainIdCharCharIdJumpJumpIdPurchasesRoute,
    ChainChainIdCharCharIdJumpJumpIdIndexRoute:
      ChainChainIdCharCharIdJumpJumpIdIndexRoute,
    ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRoute:
      ChainChainIdCharCharIdJumpJumpIdSubsystemSubtypeIdRoute,
    ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRoute:
      ChainChainIdCharCharIdJumpJumpIdSuppSupplementIdRoute,
  }

const ChainChainIdCharCharIdJumpJumpIdRouteWithChildren =
  ChainChainIdCharCharIdJumpJumpIdRoute._addFileChildren(
    ChainChainIdCharCharIdJumpJumpIdRouteChildren,
  )

interface ChainChainIdCharCharIdRouteChildren {
  ChainChainIdCharCharIdItemsRoute: typeof ChainChainIdCharCharIdItemsRouteWithChildren
  ChainChainIdCharCharIdSummaryRoute: typeof ChainChainIdCharCharIdSummaryRouteWithChildren
  ChainChainIdCharCharIdJumpJumpIdRoute: typeof ChainChainIdCharCharIdJumpJumpIdRouteWithChildren
}

const ChainChainIdCharCharIdRouteChildren: ChainChainIdCharCharIdRouteChildren =
  {
    ChainChainIdCharCharIdItemsRoute:
      ChainChainIdCharCharIdItemsRouteWithChildren,
    ChainChainIdCharCharIdSummaryRoute:
      ChainChainIdCharCharIdSummaryRouteWithChildren,
    ChainChainIdCharCharIdJumpJumpIdRoute:
      ChainChainIdCharCharIdJumpJumpIdRouteWithChildren,
  }

const ChainChainIdCharCharIdRouteWithChildren =
  ChainChainIdCharCharIdRoute._addFileChildren(
    ChainChainIdCharCharIdRouteChildren,
  )

interface ChainChainIdRouteChildren {
  ChainChainIdAddDocRoute: typeof ChainChainIdAddDocRoute
  ChainChainIdConfigRoute: typeof ChainChainIdConfigRouteWithChildren
  ChainChainIdShareRoute: typeof ChainChainIdShareRoute
  ChainChainIdIndexRoute: typeof ChainChainIdIndexRoute
  ChainChainIdCharCharIdRoute: typeof ChainChainIdCharCharIdRouteWithChildren
}

const ChainChainIdRouteChildren: ChainChainIdRouteChildren = {
  ChainChainIdAddDocRoute: ChainChainIdAddDocRoute,
  ChainChainIdConfigRoute: ChainChainIdConfigRouteWithChildren,
  ChainChainIdShareRoute: ChainChainIdShareRoute,
  ChainChainIdIndexRoute: ChainChainIdIndexRoute,
  ChainChainIdCharCharIdRoute: ChainChainIdCharCharIdRouteWithChildren,
}

const ChainChainIdRouteWithChildren = ChainChainIdRoute._addFileChildren(
  ChainChainIdRouteChildren,
)

interface JumpdocDocIdRouteChildren {
  JumpdocDocIdIndexRoute: typeof JumpdocDocIdIndexRoute
}

const JumpdocDocIdRouteChildren: JumpdocDocIdRouteChildren = {
  JumpdocDocIdIndexRoute: JumpdocDocIdIndexRoute,
}

const JumpdocDocIdRouteWithChildren = JumpdocDocIdRoute._addFileChildren(
  JumpdocDocIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  GuideRoute: GuideRoute,
  JumpdocLoadingRoute: JumpdocLoadingRoute,
  PortalRoute: PortalRoute,
  PurchasesRoute: PurchasesRoute,
  UserimagesRoute: UserimagesRoute,
  ChainChainIdRoute: ChainChainIdRouteWithChildren,
  JumpdocDocIdRoute: JumpdocDocIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
